# Generated by Django 5.2.7 on 2025-11-23 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='parcel',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='geom_wkt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='commune',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='voivodeship',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='area_ha',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='street',
        ),
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together={('user', 'parcel_id')},
        ),
    ]
