# Generated by Django 5.2.7 on 2025-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_data', '0002_alter_parcel_options_alter_parcel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='name',
        ),
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
